export const ERROR_REGISTER_CLIENTS = 'ERROR_REGISTER_CLIENTS'
export const REGISTER_CLIENTS = 'REGISTER_CLIENTS'
export const REMOVE_CLIENT = 'REMOVE_CLIENT'
export const REMOVE_CLIENT_ERR = 'REMOVE_CLIENT_ERR'